### ISSUE TITLE
when building html tikz can't find include image(png)

### ISSUE THREAD

**Issue by gdbdzgd** [sphinx-contrib/tikz#10]
System Message: WARNING/2 (\usetikzlibrary{shapes.geometric} \tikzset{node distance= 5cm and 2cm} \tikzstyle{naveqs} = [fill=blue!15, draw ,text width =6em, minimum height=5em ,rounded corners] \tikzstyle{naveqs1} = [fill=blue!15, draw ,text width =6em, minimum height=8em ,rounded corners] \tikzstyle{diamonds} = [shape=diamond,fill=white, draw=black,minimum height=2em,line width=0.5pt] \node[naveqs] (object) at (-0,2) {OBJ:User}; \node[naveqs1] (decision) at (4,-0.5) {}; \node[naveqs] (subject1) at (9,2) {SUBJ:Device}; \node[naveqs] (subject2) at (9,-2) {SUBJ:File}; \node[below right] at (decision.north west) {Policy}; \node[minimum width=2em] (den) at (1,-1) {denied}; \node[minimum width=2em] (ok) at (4,-4) {Pass}; \node at (-2.3,2.1) {\includegraphics[scale=0.3]{_static/Pictures/user.png}}; \node at (9,3.8) {\includegraphics[scale=0.18]{_static/Pictures/file.png}}; \node at (9,-0.4) {\includegraphics[scale=0.1]{_static/Pictures/device.png}}; \node[diamonds] (dia) at (4,-1) {}; \path [draw, - ] (object) -- (decision); \path [draw, - ] (decision.15) -- (subject1.west); \path [draw, - ] (decision.15) -- (subject2.west); \path [draw, - ] (den.east) -- (dia); \path [draw, - ] (ok.north) -- (dia);)

! Unable to load picture or PDF file \'_static/Pictures/user.png\'. <to be read again> } l.24 ...hics[scale=0.3]{_static/Pictures/user.png} }; LaTeX Warning: File `_static/Pictures/file.png\' not found on input line 25. ! Unable to load picture or PDF file \'_static/Pictures/file.png\'. <to be read again> } l.25 ...ics[scale=0.18]{_static/Pictures/file.png} }; LaTeX Warning: File `_static/Pictures/device.png\' not found on input line 26. ! Unable to load picture or PDF file \'_static/Pictures/device.png\'. <to be read again> } l.26 ...cs[scale=0.1]{_static/Pictures/device.png} }; [1] (./tikz-d22019dad9955c0d4ee3fd6068b9fda3b9803d2c.aux) ) (see the transcript file for additional information) Output written on tikz-d22019dad9955c0d4ee3fd6068b9fda3b9803d2c.pdf (1 page). Transcript written on tikz-d22019dad9955c0d4ee3fd6068b9fda3b9803d2c.log. '

**Comment by philexander** [comment]
Note that `includegraphics` is now supported: https://github.com/sphinx-contrib/tikz#configuration
