### ISSUE TITLE
New option to add LaTeX packages in addition to defaults amsmathn and pgfplots

### ISSUE THREAD

**Issue by Silverspur** [sphinx-contrib/tikz#16]
It would be nice to provide an option to add latex packages to the LaTeX document header used to render the TikZ figure. The option could be named 'packages' and work similarly to the 'libs' option for TikZ libraries.

**Comment by philexander** [comment]
In contrast to TikZ libraries, LaTeX packages come with options. This would ask for a more complex configuration interface.
Moreover, you can add LaTeX packages the standard way by configuring `latex_elements['preamble']` or `tikz_latex_preamble`.
