### ISSUE TITLE
'StandaloneHTMLBuilder' object has no attribute 'warn'

### ISSUE THREAD

**Issue by rpuntaie** [sphinx-contrib/tikz#2]
With the current pypi version of sphinxcontrib-tikz and sphinx-build version 2.1.1 I get this error:

```
'StandaloneHTMLBuilder' object has no attribute 'warn'"
```

This might concern other sphinxcontrib packages as well.

**Comment by SophieAltenburg** [comment]
[sphinx-err-6926akz4.log](https://github.com/sphinx-contrib/tikz/files/4550274/sphinx-err-6926akz4.log)

**Comment by philexander** [comment]
Solved in version 0.4.13, see https://github.com/sphinx-contrib/tikz/commit/650d8ac29a8f9f1a6db643c2422745b56655e7c8
