### ISSUE TITLE
Failing sphinx if a tikz figure cannot be created

### ISSUE THREAD

**Issue by obonaventure** [sphinx-contrib/tikz#3]
Hello,

The current tikz extension fails silently. If there is a problem with the tikz code for a figure (e.g. syntax error, missing ;, ...) included in a sphinx document, sphinx outputs the latex log but continues its processing. Is there a way to indicate the error to sphinx so that it can fails. This would be useful for continuous integration tests that try to validate the correctness of changes to a sphinx document.

Thanks

**Comment by jgori-ouistiti** [comment]
Hi,
I want to support obonaventure's issue, I have the same problem, where the build on github actions passes even though there are fails on the tikz part.
Thank you for the great tool
